name: Jerry_and_Cheese
description: A simple StageXL web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: zkx1022 <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  stagexl: ^1.1.0
  sqljocky5: ^2.2.0


dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0

